type Props = { clone?: boolean };
const image = (name: string) => `/images/${name}`;
function Photo({ src, alt, className = '' }: { src: string; alt: string; className?: string }) {
  return <img src={image(src)} alt={alt} className={`photo ${className}`} loading="lazy" width="1200" height="1500" />;
}
export default function TherapyPage({ clone = false }: Props) {
  const ref = (n: number) => `reference-${n}.${n === 0 || n === 7 || n === 12 ? 'png' : 'jpg'}`;
  const services = clone ? [
    ['Adults', 'Feeling stuck or overwhelmed? We help adults find clarity, build resilience, and move forward with confidence by addressing the root causes of anxiety, stress, and emotional pain.', ref(4)],
    ['Couples', 'Relationships require effort, and we’re here to help you strengthen yours. We guide couples through challenges like communication breakdowns and trust issues, helping you rebuild intimacy and strengthen your relationship.', ref(5)],
    ['Children & Teens', 'Kids need support, too. We help them process big emotions, cope with challenging family situations, build coping skills, and feel understood, while also working closely with their parents to create a nurturing environment.', ref(6)],
  ] : [
    ['Anxiety & panic', 'When your mind won’t slow down and your body stays on alert, you deserve support. Anxiety therapy in Santa Monica brings together CBT, mindfulness and body-oriented work to help you understand your patterns and find steadier ways through the day.', 'coast.jpg'],
    ['Trauma & EMDR', 'Past experiences can keep affecting how you feel in the present. Trauma therapy offers space to work through them carefully, using EMDR and body-oriented techniques with an emphasis on safety, stabilization and your pace.', 'nature.jpg'],
    ['Burnout & perfectionism', 'You may look like you’re managing while feeling exhausted inside. Therapy offers entrepreneurs, creatives and professionals a place to slow down, explore the pressure they carry and develop more sustainable ways of living and working.', 'quiet.jpg'],
  ];
  const expertise = clone ? ['Dissociation','Trauma','Family conflict','Special needs parenting','Depression','Marriage','Anxiety','Relationships','Children','Teens','Intimacy & connection'] : ['Anxiety','Panic','Trauma','Burnout','Perfectionism','Chronic stress','Overthinking','Emotional regulation','CBT','EMDR','Mindfulness'];
  const specialty = clone ? [
    ['Trauma','We don’t always know when and how we’ve experienced trauma. In therapy, we’ll work together to help you process your past, understand what’s causing you to stay “stuck,” and regain a sense of safety, control, and hope. You don’t have to carry your burdens alone.'],
    ['Dissociation','The feeling of losing time, hearing conflicting voices, or questioning your sense of self can be overwhelming. In therapy, we’ll help you understand these experiences, recognize your own triggers, and create a sense of balance and identity so that you can feel more grounded.'],
    ['EMDR','Eye Movement Desensitization and Reprocessing (EMDR) is a powerful therapeutic technique that helps process and heal trauma by reworking how painful memories are stored in your brain. This allows you to find relief and move toward lasting healing.'],
    ['Special Needs Parenting','Parenting a child with special needs presents unique challenges and complex emotions. We provide compassionate support through lived experience and expertise to help you navigate this journey with tools, understanding, and self-care.'],
  ] : [
    ['Understanding your patterns','Together, we can explore how worry, internal pressure and earlier experiences affect your relationships, confidence and daily life.'],
    ['Working with mind and body','CBT, EMDR, mindfulness and body-oriented techniques make room for both the emotional and physical sides of what you’re experiencing.'],
    ['Moving at your pace','Trauma work is paced carefully, with attention to safety and stabilization. There is space for reflection alongside practical tools.'],
    ['Making room for yourself','Our work can support insight, resilience and a stronger relationship with yourself, alongside more sustainable ways of living and working.'],
  ];
  return <div className={clone ? 'site clone' : 'site redesign'}>
    <a className="skip" href="#main">Skip to content</a>
    <aside className="demo-bar">{clone ? 'REFERENCE CLONE · INTERNSHIP STUDY' : 'FICTIONAL PRACTICE · WEBSITE CONCEPT'}<a href={clone ? '/' : '/clone/'}>{clone ? 'View redesign' : 'View reference clone'}</a></aside>
    <header className="header flex items-center justify-between">
      <a className="brand" href="#main">{clone ? <img src={image(ref(0))} alt="Conejo Valley Family Counseling" width="330" height="90" /> : <><span>Dr. Maya Reynolds</span><small>PSYD · CLINICAL PSYCHOLOGIST</small></>}</a>
      <nav aria-label="Main navigation" className="desktop-nav flex items-center gap-8">
        <a href="#about">About</a><a href="#services">{clone ? 'Our team' : 'Services'}</a><a href="#expertise">Specialties</a><a href="#approach">Methods</a><a href={clone ? "https://www.conejovalleycounseling.com/faqs" : "#faqs"}>FAQs</a><a className="oval" href="#contact">Contact</a>
      </nav>
      <details className="mobile-nav"><summary aria-label="Open navigation">Menu</summary><nav aria-label="Mobile navigation"><a href="#about">About</a><a href="#services">Services</a><a href="#approach">Approach</a><a href={clone ? "https://www.conejovalleycounseling.com/faqs" : "#faqs"}>FAQs</a><a href="#contact">Contact</a></nav></details>
    </header>
    <main id="main">
      <section className="hero">
        <img className="hero-image" src={image(clone ? ref(1) : 'coast.jpg')} alt={clone ? 'Family together on the beach' : 'A quiet stretch of California coastline'} width="1200" height="1500" fetchPriority="high" />
        <div className="hero-copy">
          <p className="eyebrow">{clone ? 'Online & in-person counseling in Newbury Park & across CA' : 'In-person in Santa Monica · Online across California'}</p>
          <h1>{clone ? <>Rebuild your foundation on solid ground and finally begin to <em>thrive.</em></> : <>Anxiety & trauma therapy in Santa Monica.<br /><em>Room to feel like you.</em></>}</h1>
          <p>{clone ? 'Specialized therapy for adults, couples, teens, and children to reflect, heal, and grow.' : 'Warm, collaborative therapy for adults navigating anxiety, past experiences and the pressure to keep going.'}</p>
          <a className="text-link" href="#contact">{clone ? 'Book an appointment' : 'Explore working together'}</a>
        </div>
        <Photo src={clone ? ref(2) : 'nature.jpg'} alt={clone ? 'Child playing near the shore' : 'Soft light and coastal textures'} className="hero-peek" />
      </section>
      <section className="intro section-pad" aria-labelledby="intro-title">
        <h2 id="intro-title">{clone ? 'You’re holding onto hope that life can be better than it is right now.' : 'You can be doing everything right and still feel overwhelmed.'}</h2>
        <p className="eyebrow">{clone ? 'At Conejo Valley Family Counseling we want to make that hope a reality.' : 'You don’t have to carry it all on your own.'}</p>
        <p className="intro-lead">{clone ? 'Whether you’re an adult seeking personal growth, looking to work through your trauma, a couple working on your relationship, or a parent looking for support for your child, we provide a compassionate and safe space to help you navigate all of life’s ups and downs.' : 'Maybe the worry doesn’t switch off. Maybe you feel exhausted, on edge, or disconnected from yourself after years of pushing through stress. Therapy is a place to slow down and make sense of what you’re experiencing.'}</p>
        <div className="intro-grid grid md:grid-cols-2"><Photo src={clone ? ref(3) : 'quiet.jpg'} alt={clone ? 'Gentle ocean waves under a cloudy sky' : 'A peaceful place for a moment of reflection'} /><p>{clone ? 'First and foremost, we believe what you’re going through is real, valid, and worthy of support. Our team offers clients in the Newbury Park area and across CA an environment to discover a new life and a deeper sense of self in the midst of their struggles. As we tap into the power of connection and understanding, you can find your footing again and take a transformative path forward.' : 'I’m Dr. Maya Reynolds, a licensed clinical psychologist in Santa Monica. I work with adults who often appear functional on the outside while struggling with worry, tension or the effects of past experiences. Our work makes room for your story, your body’s responses and the changes that matter to you.'}</p></div>
      </section>
      <section id="services" className="services section-pad">
        <h2>{clone ? <>Who we <em>help</em></> : <>Support for what you’re <em>carrying.</em></>}</h2>
        <div className="service-grid grid md:grid-cols-3 gap-10">{services.map(([title,copy,src])=><article key={title}><Photo src={src} alt={clone ? `${title} at the California coast` : ''} /><h3>{title}</h3><p>{copy}</p></article>)}</div>
      </section>
      <section id="expertise" className="expertise section-pad">
        <Photo src={clone ? ref(7) : 'nature.jpg'} alt="" />
        <div><h2>{clone ? 'You deserve a place where your story is heard, valued, and understood. Nothing will be too heavy for us to carry together.' : 'A place to be understood, without having to hold everything together.'}</h2><h3>{clone ? 'Our areas of expertise' : 'What we can work with'}</h3><ul className="expertise-list flex flex-wrap">{expertise.map(t=><li key={t}>{t}</li>)}</ul>{clone && <p className="eyebrow">…and more.</p>}</div>
      </section>
      <section id="approach" className="approach section-pad">
        <p className="eyebrow">{clone ? 'How we work' : 'A warm, grounded approach'}</p>
        <h2>{clone ? 'We’re here to make a difference.' : 'Practical tools. Space for depth.'}</h2>
        <div className="approach-grid grid md:grid-cols-2"><Photo src={clone ? ref(8) : 'quiet.jpg'} alt={clone ? 'A mother and child dancing on the beach' : 'Quiet natural surroundings'} /><div><p className="eyebrow">{clone ? 'The clients we work with are balancing so many things at once, it’s often hard for them to put themselves first.' : 'You’re an active part of the process.'}</p><p>{clone ? 'Here, your needs are always top priority. Our team takes the time to deeply listen to our clients in order to truly understand their story and their struggles. We recognize that no two people are the same and that personalized therapy means an intentional, tailored approach. (You won’t find anything “one-size-fits-all” here.) If you’re ready to do the work, we’re ready to help.' : 'Sessions are collaborative and structured enough to feel supportive, while leaving room for reflection. I draw on cognitive-behavioral therapy, EMDR, mindfulness and body-oriented techniques to understand both the emotional and physical sides of your experience.'}</p><p>{clone ? 'Sometimes we may gently challenge you to look at things differently and other times we may explore your emotions, all while encouraging you to practice what you’ve learned in your daily life. We take what we do seriously because we know how important it is for you to heal from what’s hurting you, discover a fulfilling life, and build meaningful relationships.' : 'When we work with trauma, we move carefully. Safety, stabilization and feeling more regulated in everyday life guide the pace. The goal is to support insight, resilience and a stronger relationship with yourself over time.'}</p><a className="text-link" href="#about">{clone ? 'Learn more about us' : 'Meet Dr. Reynolds'}</a></div></div>
      </section>
      <section id="about" className="specialties section-pad">
        <Photo src={clone ? ref(9) : 'maya.png'} alt={clone ? 'Family of four facing the ocean at sunset' : 'Dr. Maya Reynolds, PsyD — supplied fictional therapist portrait'} />
        <div><h2>{clone ? 'Honoring where you’ve been & helping shape where you’re headed.' : 'Meet Dr. Maya Reynolds, PsyD.'}</h2><h3>{clone ? 'Our specialties include…' : 'Licensed clinical psychologist · Santa Monica'}</h3>{!clone && <p>I work with adults facing anxiety, panic, trauma and professional burnout. Many are thoughtful, high-achieving people navigating perfectionism, chronic stress or a sense of disconnection. My approach combines practical tools with space to explore the deeper patterns shaping your life.</p>}<div className="specialty-grid grid sm:grid-cols-2 gap-8">{specialty.map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p>{clone && <a className="text-link" href="#contact">Learn more</a>}</article>)}</div></div>
      </section>
      {!clone && <section id="office" className="office section-pad"><div className="office-heading grid md:grid-cols-2 gap-10"><div><p className="eyebrow">Our office</p><h2>A calm space.<br /><em>A little room to exhale.</em></h2></div><div><p>Natural light, comfortable seating and an uncluttered setting. My Santa Monica office is a quiet, private space designed to feel grounding, so there’s room to settle in and focus on you.</p><p className="office-location">Santa Monica, California</p><p>In-person sessions here, or secure telehealth from anywhere in California.</p></div></div><div className="office-images grid md:grid-cols-2 gap-6"><Photo src="office-1.jpg" alt="Dr. Reynolds’s supplied office: bright therapy room with neutral seating and natural light" /><Photo src="office-2.jpg" alt="Dr. Reynolds’s supplied office: comfortable seating in a quiet, uncluttered room" /></div></section>}
      {!clone && <section id="faqs" className="faq section-pad grid md:grid-cols-2 gap-12"><div><p className="eyebrow">A few things to know</p><h2>Before we<br /><em>begin.</em></h2></div><div>{[
        ['Who do you work with?', 'I work with adults, including entrepreneurs, creatives and professionals, who are navigating anxiety, panic, trauma, burnout, perfectionism or chronic stress.'],
        ['Can we meet online?', 'Yes. I offer secure telehealth for clients located in California, as well as in-person sessions at my Santa Monica office.'],
        ['What is your approach?', 'My approach is warm, collaborative and grounded. I integrate CBT, EMDR, mindfulness and body-oriented techniques, with space for both practical tools and reflection.'],
        ['How do you approach trauma work?', 'Trauma work is paced carefully, with an emphasis on safety and stabilization. We pay attention to how you feel both in sessions and in your everyday life.'],
      ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>}
      <section id="contact" className="contact section-pad">
        <Photo src={clone ? ref(10) : 'coast.jpg'} alt={clone ? 'A person collecting seashells on a beach' : 'The California shoreline in soft daylight'} />
        <div><p className="eyebrow">{clone ? 'Schedule an appointment' : 'Take the next step at your pace'}</p><h2>{clone ? <>Find a therapist who is the right fit for <em>you.</em></> : <>You don’t have to figure it all out <em>alone.</em></>}</h2><p>{clone ? 'Coming to therapy is a courageous decision, and connecting with the right kind of therapist makes all the difference. We understand that your journey is personal, and we’re here to support you with care and understanding every step of the way. Each member of our team brings dedicated expertise and a commitment to support you in your struggles.' : 'If you’re looking for a warm, collaborative space to work through what you’re carrying, my approach may be a good fit. In-person therapy is available in Santa Monica, with secure telehealth across California.'}</p>{clone ? <><p>Click the button below to schedule an appointment.</p><a className="oval" href="https://www.conejovalleycounseling.com/contact">Book now</a></> : <details className="contact-demo"><summary className="oval">Explore the next step</summary><p>This is a fictional practice concept for an internship assignment. No appointments or messages are collected. A verified contact method would be connected before a real launch.</p></details>}</div>
        <Photo src={clone ? ref(11) : 'nature.jpg'} alt="" className="contact-peek" />
      </section>
    </main>
    <footer className="footer section-pad"><div className="footer-grid grid md:grid-cols-4 gap-10"><div className="footer-brand">{clone ? 'Conejo Valley' : 'Dr. Maya Reynolds'}<small>{clone ? 'FAMILY COUNSELING' : 'PSYD · CLINICAL PSYCHOLOGIST'}</small><p>{clone ? 'We want to make getting started simple. You’re welcome to come into our office in Newbury Park or schedule virtual appointments from anywhere in CA—whatever works best for you.' : 'Warm, collaborative therapy for adults. In-person in Santa Monica and online across California.'}</p></div><div><h3>Navigate</h3><a href="#main">Home</a><a href="#about">About</a><a href={clone ? "https://www.conejovalleycounseling.com/faqs" : "#faqs"}>FAQs</a><a href="#contact">Contact</a></div><div><h3>{clone ? 'Contact' : 'Location'}</h3>{clone ? <><p>925 Broadbeck Dr<br />Suites 200 and 225<br />Newbury Park, CA 91320</p><a href="mailto:info@conejovalleycounseling.com">info@conejovalleycounseling.com</a><a href="tel:8052423120">805.242.3120</a></> : <><p>Santa Monica, CA 90401</p><p>In-person & California telehealth</p><a href="#office">Our office</a></>}</div><div><h3>{clone ? 'Our team' : 'Areas of focus'}</h3>{(clone ? ['Jennifer Anderson','Heather Williams-Baumgart','Autumn Bodily','Candace Bletscher','Samantha Johnson','Rosa Gomez','Chad Flores'] : ['Anxiety & panic','Trauma & EMDR','Burnout & perfectionism']).map(t=><a key={t} href={clone ? 'https://www.conejovalleycounseling.com/therapists-newbury-park' : '#services'}>{t}</a>)}</div></div><div className="footer-bottom"><p>{clone ? 'Reference reproduction for evaluation. Original content and imagery belong to Conejo Valley Family Counseling.' : 'Fictional therapist website concept · No clinical services or appointments offered.'}</p><a href={clone ? '/' : '/clone/'}>{clone ? 'View redesign' : 'View reference clone'}</a></div></footer>
  </div>;
}
